minimal_browser_list: &minimal_browser_list
  - chrome
  - firefox

extended_browser_list: &extended_browser_list
  - chrome
  - firefox
  - edge

tests:
  # GEO
  - test_name: integ_react_geo_display_map
    desc: 'Display Map'
    framework: react
    category: geo
    sample_name: [display-map]
    spec: display-map
    # Temp fix:
    browser: [chrome]
  - test_name: integ_react_geo_search_outside_map
    desc: 'Search Outside Map'
    framework: react
    category: geo
    sample_name: [search-outside-map]
    spec: search-outside-map
    # Temp fix:
    browser: [chrome]
  # - test_name: integ_javascript_geo_display_map
  #   desc: 'Display Map'
  #   framework: javascript
  #   category: geo
  #   sample_name: [display-map-static]
  #   spec: display-map-static
  #   browser: *minimal_browser_list
  #   amplifyjs_dir: true
  # - test_name: integ_javascript_geo_search_outside_map
  #   desc: 'Search Outside Map'
  #   framework: javascript
  #   category: geo
  #   sample_name: [search-outside-map-static]
  #   spec: search-outside-map-static
  #   browser: *minimal_browser_list
  #   amplifyjs_dir: true
