version: 2.1

executors:
  build-executor:
    docker:
      - image: cypress/base:12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    resource_class: large
    working_directory: ~/maplibre-gl-js-amplify

  integ-test-executor:
    docker:
      - image: cypress/included:5.2.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    resource_class: large

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn link
      - save_cache:
          key: amplify-maplibre-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - persist_to_workspace:
          root: /root
          paths:
            - maplibre-gl-js-amplify

  unit_test:
    executor: build-executor
    steps:
      - attach_workspace:
          at: /root
      - run: yarn test

  integ_setup:
    executor: build-executor
    working_directory: ~/
    steps:
      - run:
          name: "Clone Amplify JS Samples repo, install cypress, install react samples authenticator and link amplify packages"
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            echo $SSH_HOST_PUBLIC_KEY >> ~/.ssh/known_hosts
            git clone $AMPLIFY_JS_SAMPLES_STAGING_URL
            cd amplify-js-samples-staging
            yarn
      - save_cache:
          key: maplibre-gl-js-amplify-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress
      - persist_to_workspace:
          root: /root
          paths:
            - amplify-js-samples-staging

  integ_test:
    executor: integ-test-executor
    working_directory: ~/
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          key: maplibre-gl-js-amplify-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
      - run:
          name: "Change directory into build and run link"
          command: |
            cd ~/maplibre-gl-js-amplify/
            yarn link
      - run:
          name: "Link packages into samples staging root"
          command: |
            cd ~/amplify-js-samples-staging
            yarn link maplibre-gl-js-amplify
      - run:
          name: "Run cypress test"
          command: |
            cd ~/amplify-js-samples-staging
            yarn ci:test react geo display-map
      - store_artifacts:
          path: ~/amplify-js-samples-staging/cypress/videos
      - store_artifacts:
          path: ~/amplify-js-samples-staging/cypress/screenshots

releasable_branches: &releasable_branches
  branches:
    only:
      - main

workflows:
  integration_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integ_setup:
          requires:
            - build
          filters:
            <<: *releasable_branches
      - integ_test:
          requires:
            - build
            - integ_setup
          filters:
            <<: *releasable_branches
