version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:12
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    working_directory: ~/maplibre-gl-js-amplify
    steps:
      - checkout # check out the code in the project directory
      - run: yarn
      - run: yarn build
      - run: yarn test
