version: 2.1

executors:
  build-executor:
    docker:
      - image: cypress/base:16.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    resource_class: large
    working_directory: ~/maplibre-gl-js-amplify

  integ-test-executor:
    docker:
      - image: cypress/included:8.7.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    resource_class: large

commands:
  prepare_test_env:
    steps:
      - attach_workspace:
          at: /root
      - restore_cache:
          key: maplibre-gl-js-amplify-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
      - run:
          name: "Change directory into build and run link"
          command: |
            cd ~/maplibre-gl-js-amplify/
            yarn link
      - run:
          name: "Link packages into samples staging root"
          command: |
            cd ~/amplify-js-samples-staging
            yarn link maplibre-gl-js-amplify

  integ_test_js:
    parameters:
      test_name:
        type: string
      framework:
        type: string
      category:
        type: string
      sample_name:
        type: string
      spec:
        # optional - the script will use sample_name by default
        type: string
        default: ""
      browser:
        type: string
        default: ""
    steps:
      - run:
          name: "Run cypress test << parameters.test_name >>"
          command: |
            cd ~/amplify-js-samples-staging
            yarn ci:test << parameters.framework >> << parameters.category >> << parameters.sample_name >> << parameters.spec >> << parameters.browser >>
      - store_artifacts:
          path: ~/amplify-js-samples-staging/cypress/videos
      - store_artifacts:
          path: ~/amplify-js-samples-staging/cypress/screenshots

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn link
      - save_cache:
          key: amplify-maplibre-ssh-deps-{{ .Branch }}
          paths:
            - ~/.ssh
      - persist_to_workspace:
          root: /root
          paths:
            - maplibre-gl-js-amplify

  unit_test:
    executor: build-executor
    steps:
      - attach_workspace:
          at: /root
      - run: yarn test

  integ_setup:
    executor: build-executor
    working_directory: ~/
    steps:
      - run:
          name: "Clone Amplify JS Samples repo, install cypress, install react samples authenticator and link amplify packages"
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            echo $SSH_HOST_PUBLIC_KEY >> ~/.ssh/known_hosts
            git clone $AMPLIFY_JS_SAMPLES_STAGING_URL
            cd amplify-js-samples-staging
            yarn
      - save_cache:
          key: maplibre-gl-js-amplify-{{ .Branch }}-{{ checksum "amplify-js-samples-staging/yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress
      - persist_to_workspace:
          root: /root
          paths:
            - amplify-js-samples-staging

  integ_test_cra4:
    executor: integ-test-executor
    working_directory: ~/
    steps:
      - prepare_test_env
      - integ_test_js:
          test_name: "CRA4 React Geo Display Map"
          framework: react
          category: geo
          sample_name: cra4-display-map
          spec: display-map
      - integ_test_js:
          test_name: "CRA4 React Geo Search Outside Map"
          framework: react
          category: geo
          sample_name: cra4-search-outside-map
          spec: search-outside-map
      - integ_test_js:
          test_name: "CRA4 React Geo Geofence Control Map"
          framework: react
          category: geo
          sample_name: cra4-geofence-control-map
          spec: geofence-control-map
      - integ_test_js:
          test_name: "CRA4 TS React Geo Geofence Control Map"
          framework: react
          category: geo
          sample_name: cra4-ts-geofence-control-map
          spec: geofence-control-map

  integ_test_cra5:
    executor: integ-test-executor
    working_directory: ~/
    steps:
      - prepare_test_env
      - integ_test_js:
          test_name: "CRA5 React Geo Display Map"
          framework: react
          category: geo
          sample_name: cra5-display-map
          spec: display-map
      - integ_test_js:
          test_name: "CRA5 TS React Geo Display Map"
          framework: react
          category: geo
          sample_name: cra5-ts-display-map
          spec: display-map
      - integ_test_js:
          test_name: "CRA5 React Geo Geofence Control Map"
          framework: react
          category: geo
          sample_name: cra5-geofence-control-map
          spec: geofence-control-map

  integ_test_vite:
    executor: integ-test-executor
    working_directory: ~/
    steps:
      - prepare_test_env
      - integ_test_js:
          test_name: "Vite Geo Display Map"
          framework: vue
          category: geo
          sample_name: vite-display-map
          spec: display-map
      - integ_test_js:
          test_name: "Vite Geo Geofence Control Map"
          framework: vue
          category: geo
          sample_name: vite-geofence-control-map
          spec: geofence-control-map

  integ_test_next:
    executor: integ-test-executor
    working_directory: ~/
    steps:
      - prepare_test_env
      - integ_test_js:
          test_name: "Next Geo Display Map"
          framework: next
          category: geo
          sample_name: next-display-map
          spec: display-map
      - integ_test_js:
          test_name: "Next Geo Geofence Control Map"
          framework: next
          category: geo
          sample_name: next-geofence-control-map
          spec: geofence-control-map

releasable_branches: &releasable_branches
  branches:
    only:
      - main
      - integ-test

workflows:
  integration_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integ_setup:
          requires:
            - build
          filters:
            <<: *releasable_branches
      - integ_test_cra4:
          requires:
            - integ_setup
          filters:
            <<: *releasable_branches
      - integ_test_cra5:
          requires:
            - integ_setup
          filters:
            <<: *releasable_branches
      - integ_test_ts:
          requires:
            - integ_setup
          filters:
            <<: *releasable_branches
