# Copied from - https://github.com/aws-amplify/amplify-js/blob/main/.github/actions/load-verdaccio-with-amplify-js/action.yml

name: Setup Amplify Integration Test Package
description: Checks out "amplify-js-samples-staging" and builds the package with caching

inputs:
  GH_TOKEN_STAGING_READ:
    description: The token that grants read access to the sample staging repo
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3 https://github.com/actions/cache/commit/5a3ec84eff668545956fd18022155c47e93e2684
      id: cache-samples-staging-build
      with:
        key: aws-amplify-js-samples-staging-build-${{ github.sha }}
        path: |
          ./amplify-js-samples-staging/node_modules
          /home/runner/.cache/Cypress
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Checkout staging repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 https://github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: ${{ github.repository_owner }}/amplify-js-samples-staging
        path: amplify-js-samples-staging
        token: ${{ inputs.GH_TOKEN_STAGING_READ }}

    # We test on the staging branch that corresponds to the amplify-js branch
    #   when it exists and test on the default branch `main` otherwise
    - name: Staging repo branch selection
      shell: bash
      working-directory: ./amplify-js-samples-staging
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        if git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1; then
            # Branch exists, checkout and echo success message
            git fetch origin $BRANCH
            git checkout $BRANCH
            echo "Checked out branch: $BRANCH"
        else
            # Branch doesn't exist, echo error message
            echo "Branch '$BRANCH' does not exist"
        fi

    - name: Install
      run: |
        yarn
      shell: bash
      working-directory: ./amplify-js-samples-staging
