# Copied from https://raw.githubusercontent.com/aws-amplify/amplify-js/main/.github/actions/load-verdaccio-with-amplify-js/action.yml

name: Load Verdaccio with maplibre-gl-js-amplify
description: Turn on Verdaccio and load up all of the maplibre-gl-js-amplify build artifacts

runs:
  using: 'composite'
  steps:
    - name: Start verdaccio
      run: |
        npx verdaccio@6.0.5 &
        while ! nc -z localhost 4873; do
          echo "Verdaccio not running yet"
          sleep 1
        done

        # Run your commands after verdaccio is up and running
        echo "Verdaccio is up and running, proceeding with the script..."
      shell: bash
    - name: Authenticate with Verdaccio
      shell: bash
      env:
        NPM_REGISTRY: http://localhost:4873/
        NPM_USER: verdaccio
        NPM_PASS: verdaccio
        NPM_EMAIL: verdaccio@amplify.js
      run: |
        TOKEN=$(curl -X PUT \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
        $NPM_REGISTRY-/user/org.couchdb.user:$NPM_USER | jq -r '.token')

        echo "registry=$NPM_REGISTRY
        //localhost:4873/:_authToken=$TOKEN" > ~/.npmrc

    - name: Configure registry and git
      shell: bash
      working-directory: ./maplibre-gl-js-amplify
      env:
        NPM_REGISTRY: http://localhost:4873/
        NPM_USER: verdaccio
        NPM_PASS: verdaccio
        NPM_EMAIL: verdaccio@amplify.js
      run: |
        yarn config set registry $NPM_REGISTRY
        npm set registry $NPM_REGISTRY
        git config --global user.email $NPM_EMAIL
        git config --global user.name $NPM_USER
        git status
        git --no-pager diff
    - name: Publish to verdaccio
      shell: bash
      working-directory: ./maplibre-gl-js-amplify
      run: |
        YARN_REGISTRY=http://localhost:4873/ yarn publish:unstable
        YARN_REGISTRY=http://localhost:4873/ yarn info maplibre-gl-js-amplify@unstable description
        NPM_CONFIG_REGISTRY=http://localhost:4873 npm info maplibre-gl-js-amplify@unstable version
