name: publish

on:
  push:
    branches:
      - release
      - main
      - geo

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [e2e]
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f

      - name: Use Node.js 16 x64
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 16
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install build dependencies
        run: |
          yarn

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn semantic-release
