name: publish

on:
  push:
    branches:
      - release
      - geo

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
          registry-url: "https://registry.npmjs.org"

      - name: Install build dependencies
        run: |
          yarn

      - name: publish:release
        if: github.ref == 'refs/heads/release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          yarn publish:release

      - name: publish:geo
        if: github.ref == 'refs/heads/geo'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          yarn publish:geo
