# Copied from https://github.com/aws-amplify/amplify-js/blob/main/.github/actions/node-and-build/action.yml

name: Set Node and Build
description: Checks out Amplify and builds the package
inputs:
  is-prebuild:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0 https://github.com/actions/setup-node/commit/cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      with:
        node-version: 20
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3 https://github.com/actions/cache/commit/5a3ec84eff668545956fd18022155c47e93e2684
      id: cache-build-artifacts
      with:
        path: |
          **/node_modules
          **/dist
          **/lib
          **/lib-esm/
          **/es/
          **/esm/
          **/cjs/
          **/packages/core/src/Platform/version.ts
        key: ${{ runner.os }}-build-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    # TODO We should be able to skip yarn / bootstrap if we cache enough things. Leaving because skipping causes issues.
    - name: Install
      if: inputs.is-prebuild != 'true' || steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn
      shell: bash
      working-directory: ./maplibre-gl-js-amplify
