# Copied from https://github.com/aws-amplify/amplify-js/blob/main/.github/actions/node-and-build/action.yml

name: Set Node and Build
description: Checks out Amplify and builds the package
inputs:
  is-prebuild:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 24
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0 https://github.com/actions/setup-node/commit/48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version: 24
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5 https://github.com/actions/cache/commit/27d5ce7f107fe9357f9df03efb73ab90386fccae
      id: cache-build-artifacts
      with:
        path: |
          **/node_modules
          **/dist
          **/lib
          **/lib-esm/
          **/es/
          **/esm/
          **/cjs/
          **/packages/core/src/Platform/version.ts
        key: ${{ runner.os }}-build-artifacts-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    # TODO We should be able to skip yarn / bootstrap if we cache enough things. Leaving because skipping causes issues.
    - name: Install
      if: inputs.is-prebuild != 'true' || steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn
      shell: bash
      working-directory: ./maplibre-gl-js-amplify
